language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
    - PACKAGE_VCS_URL=https://github.com/aursu/rpmbuild-php-7.3
    - BINTRAY_REPO=custom
  jobs:
    - BASE=centos7libwebpbase BUILD=centos7libwebpbuild UPLOADER=centos7bintray
    - BASE=centos8libwebpbase BUILD=centos8libwebpbuild UPLOADER=centos8bintray

before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - docker-compose -f docker-compose.base.yml build --no-cache --pull ${BASE}

before_script:
  - docker-compose build --no-cache ${BUILD}

script:
  - docker-compose up ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL ${UPLOADER}
  on:
    all_branches: true