version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.7

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  libwebpbuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos8build
          build_service: centos8build
          bintray_uploader: centos8bintray
          bintray-repo: custom
      - docker-rpmbuild/build:
          name: centos7build
          build_service: centos7build
          bintray_uploader: centos7bintray
          bintray-repo: custom