version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.6

workflows:
  libwebpbuild:
    jobs:
      - docker-rpmbuild/rpmbuild:
          package-vcs-url: https://github.com/aursu/rpmbuild-libwebp
          name: centos8libwebpbuild
          base_service: centos8libwebpbase
          build_service: centos8libwebpbuild
          bintray_uploader: centos8bintray
          bintray-repo: custom
